### ISSUE TITLE
Issue creating database when --scaling is passed to rhc create

### ISSUE THREAD

**Issue by kwheat2064** [ryanj/restify-postGIS#2]
I'm having an issue getting the database portion of the app to create when I try and create a scaled app. Anyone have any ideas as to why this may be happening? 

rhc app create --scaling parksdemo1 nodejs-0.10 postgresql-9.2 --from-code=https://github.com/ryanj/restify-postGIS.git

data already exists - bypassing db initialization step
 { [error: database "/parksdemo01" does not exist]
  name: 'error',
  length: 90,
  severity: 'FATAL',
  code: '3D000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'postinit.c',
  line: '717',
  routine: 'InitPostgres' }

**Comment by kwheat2064** [comment]
I just wanted to update that there is a bug with OpenShift when you enable scaling on an application. You'll need to edit the environment variables for each gear that you want to enable scaling on.

https://stackoverflow.com/questions/24186367/error-database-does-not-exist-on-scaled-jboss-app-on-openshift

https://help.openshift.com/hc/en-us/articles/202399310-How-to-create-and-use-environment-variables-on-the-server

This fixes the extra '/' that gets passed in to the database name during the portion of the script that loads data into the DB.

**Comment by ryanj** [comment]
Thanks for reporting @kwheat2064

**Comment by ryanj** [comment]
Confirmed - there is an extra `/` at the end of the `OPENSHIFT_POSTGRESQL_DB_URL` when scaling is enabled.  This will need to be reported here: https://bugzilla.redhat.com/

**Comment by kwheat2064** [comment]
Reported.

**Comment by ryanj** [comment]
This should be fixed now. Feel free to reopen if this comes up again
