### ISSUE TITLE
Unable to pull points from DB: Failed to load resource

### ISSUE THREAD

**Issue by emanuelfeld** [ryanj/restify-postGIS#3]
With the caution that I have zilch backend experience, points in bounding box queries appear to be failing both on the [example instance](http://nodegis-shifter.rhcloud.com/) and the forked version I spun up. Any advice on this? Thanks, Ryan!

**Comment by ryanj** [comment]
hi @emanuelfeld. 
Sorry, I didn't notice this issue. This should be fixed now.

Feel free to reopen if you hit the same issue again.
